### PR TITLE
add stylehints for betterment of UI in main.qml

### PR DESCRIPTION
**Pull request by ghost**
This makes colour more integrated to app. Test the app in the desktop before publishing to openstore using the command `clickable desktop`

### CODE REVIEW

**Comment by patrickjane** [comment]
Hi, sorry for the late reply, I was away for a couple of days and could not work on the app.

I see you have closed the PR meanwhile. What was the motiviation? Is this PR needed? If so, I can merge it.

**Comment by ghost** [comment]
Sorry, I accidentally submitted this PR without testing, only after testing that I found out that it was not useful. It did not maintain/contain the app. I actually accidentally submitted this PR only so that the colour "plant green" gets into the title plants in the title bar. If you know how to actually do that, this PR is useless.

**Comment by patrickjane** [comment]
You mean you want to have a colored page header in green? I have done this before, but it requires a bit of a hack, since background coloring is not supported on the header according to my research.

**Comment by ghost** [comment]
Yes.

**Pull request closed without merging**
