### PR TITLE
rearrange items, only flick if needed, adjust spelling, update de

### PR DESCRIPTION
**Pull request by Danfro**
1. make the page only flick if needed
2. rephrase the text how to get an api key
3. update German translation

### CODE REVIEW

**Comment by Danfro** [comment]
And here some screenshots. Now the keyboard only obscures some text but not the input box.

grafik

grafik

**Comment by patrickjane** [comment]
Okay I see, this really looks bad. However, having to move content to other places in order to not have it obstructed by the keyboard seems wrong. There must be a better solution I guess. E.g. for other cases where it just might be not possible to move the input, there must be a way to solve this too.
Did you ask in the developer group? If you ask me, moving the input to the top now does not look that great. Just remember that this is the settings page, and more settings could follow in the future. So it's meant to be a list of things. Maybe a compromise for now would be to have the first text-block, then the input, and then the second text-block? But still, there must be another way. Gonna see if I can find another solution.

Btw: I'd like to keep the divider, since its used throughout list views in Ubuntu Touch.

**Comment by Danfro** [comment]
I restored the dividers and moved back the api key field to the bottom.

To implement a fix for the keyboard issue, I rephrased the wording to make it shorter. This is also an improvement since users have less words to read. Please let me know if you agree with this.

**Comment by Danfro** [comment]
Rebase done.

**Comment by Danfro** [comment]
Btw. the rephrase trick does work for English and German. Of course it might not work for some other languages with much longer translations.

There is one implementation where the keyboard moves up I know of: terminal app.
It does set a [Loader](https://gitlab.com/ubports/development/apps/terminal-app/-/blob/main/src/app/qml/TerminalPage.qml#L290) for the keyboard. The terminal component is then anchored to the [keyboard loader's](https://gitlab.com/ubports/development/apps/terminal-app/-/blob/main/src/app/qml/TerminalPage.qml#L280) top.
Not sure if that can be applied here as well.

**Comment by patrickjane** [comment]
I am currently investigating possible solutions. I got the hint to do it like here: https://gitlab.com/dobey/authenticator-ng/-/blob/trunk/src/qml/EditPage.qml#L224-227

Or to set `anchorToKeyboard: true` on the `MainView`. Unfortunately, both solutions do not work. I will check this further and see if I can make it work.

Regarding the adjustment of the text: As you already stated yourself, this might not do the trick whenever a translator adds a translation with certain text length. Thus, the solution is not really viable. Even if all translations would be small, and the keyboard does not hide the input on _your_ device, it might on other devices. And it is not future-proof in that when more settings are added to the bottom of the list, the same issue might be there again.

So I am trying to find a way currently which moves the content when keyboard is shown regardless of child item ordering/layout.

**Comment by Danfro** [comment]
Oh, I forgot to upload a screenshot with the latest changes I made. Here it is...

grafik

**Comment by Danfro** [comment]
I updated the description to match the current state of this PR.
This is now independent from the OSK issue.

So do you like the new rephrased text? Even if it does not finally solve the OSK issue?

Please let me know what you would wish to see changed to get this merged. Or if you do not plan to merge the changes, the I could close it.

**Comment by Danfro** [comment]
Regarding the OSK I saw the discussion on Telegram too. But I had to time yet to investigate further myself. I only checked a few other apps, they seem to have the same problem.

**Comment by patrickjane** [comment]
Sorry for the late reply, I have been a bit busy these days.

Regarding the text change, I think we don't need to rephrase it, since it does not solve the OSK issue, so I would rather like to keep the existing text. 
I have adpoted your changes regarding scroll only if needed, and I added the "developer account" hint, both in my latest commit. So I think there is nothing left from this pull request?

We should keep the issue open, however, to track the OSK problematics, which must be solved. Didn't have time to investigate this further yet, but the next thing I'm gonna try is to resemble the authenticator-ng solution 1:1, since it must work when it is working for them. Maybe this is gonna solve this issue finally.

If you want to have a try on it, feel free. I think the main difference between the authenticator-ng code and ut-plants might be the structure of the settings list; they don't use `ListItem` instances. I didn't check the rest of their UI composition though. There might be more differences in their layout (page stack, main view, and so on).

**Comment by Danfro** [comment]
Good, I can close this MR then. I will try to do this later if possible on my phone.

I can't do much currently because I am not at home. Authenticator is using its own components kit if I remember right called Ergo, so might not be possible to adapt 1:1. I just discovered that [steps app](https://github.com/jranaraki/steps) is managing to move OSK too. 

--

**Comment by patrickjane** [comment]
Found this: https://stackoverflow.com/questions/33526230/keep-input-field-in-view-while-using-on-screen-keyboard

The steps mentioned there with some adjustments allowed me to provide a working fix.

Will push the update in a few minutes, maybe @Danfro you can check if it works properly on your device?

**Comment by Danfro** [comment]
Sure I can test. Thanks for digging into this. :+1:  Just let me know when you are ready. But maybe we should rather move this discussion to the related issue #6  that keep filling up this closed PR?

**Comment by patrickjane** [comment]
Yeah you‘re right. Btw update should be available now.

**Comment by Danfro** [comment]
I think components can be attached to the keyboard somehow. But not
sure how reliable that works. But you are right, there must be a way.

Maybe until more settings come, this workaround to move the input box
is the easier option?

The design is up to you and always down to personal preferences. My PR
is of course only a suggestion. But I removed dividers from core apps
wherever I found them. :-)

But I can also reenable them for this MR. No problem.

**Comment by patrickjane** [comment]
Hm? I think everything has been adopted. Except for the dividers. But your original 3 points are now implemented. Did I miss anything?

**Comment by Danfro** [comment]
I am sorry, no idea where that message came from NOW. I did not write anything today.

I think I wrote that weeks ago. Maybe it got stuck? Maybe it was only a draft? Don't know right now. Sure now not related anymore.

--

**Pull request closed without merging**
